/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Prestador;
import Modelo.Productor;
import Modelo.Servicio;
import Modelo.TipoServicio;
import controlador.Controlador;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author nico2
 */
public class ventanaListado extends javax.swing.JFrame {
    private final Controlador c;
    private final JFrame vAnterior;

    /**
     * Creates new form ventanaListado
     */
    public ventanaListado(Controlador c, JFrame vAnterior) {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(245,245,245));
        this.c=c;
        this.vAnterior=vAnterior;
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPrestador = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaServiciosPrestador = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaServicios = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaPrestadoresServicios = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaProductor = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaHistorialPuntajes = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label6 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(478, 400));

        listaPrestador.setBackground(new java.awt.Color(216, 249, 225));
        listaPrestador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaPrestador.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPrestadorValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaPrestador);

        jLabel1.setText("Listado de prestadores");

        jLabel4.setText("Lista de servicios");

        listaServiciosPrestador.setBackground(new java.awt.Color(216, 249, 225));
        listaServiciosPrestador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaServiciosPrestador.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaServiciosPrestadorValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(listaServiciosPrestador);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1674, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Prestadores", jPanel1);

        listaServicios.setBackground(new java.awt.Color(216, 249, 225));
        listaServicios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaServiciosValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listaServicios);

        jLabel3.setText("Listado de servicios existentes");

        listaPrestadoresServicios.setBackground(new java.awt.Color(216, 249, 225));
        listaPrestadoresServicios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaPrestadoresServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPrestadoresServiciosValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(listaPrestadoresServicios);

        jLabel5.setText("Prestadores de ese servicio");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addContainerGap(1676, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Servicios", jPanel3);

        listaProductor.setBackground(new java.awt.Color(216, 249, 225));
        listaProductor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaProductor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaProductorValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(listaProductor);

        listaHistorialPuntajes.setBackground(new java.awt.Color(216, 249, 225));
        listaHistorialPuntajes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaHistorialPuntajes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaHistorialPuntajesValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(listaHistorialPuntajes);

        jLabel6.setText("Historial de puntajes");

        jLabel2.setText("Listado de productores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1671, 1671, 1671))
        );

        jTabbedPane2.addTab("Productores", jPanel2);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\nico2\\Downloads\\icons8-resultados-de-la-prueba-filled-50.png")); // NOI18N

        label6.setBackground(new java.awt.Color(245, 245, 245));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("Listados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.vAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

     public void limpiar(){
        //Se crean las listas
        DefaultListModel modelolista = new DefaultListModel();
        this.listaPrestador.setModel(modelolista);
        this.listaProductor.setModel(modelolista);
        this.listaServiciosPrestador.setModel(modelolista);
        this.listaHistorialPuntajes.setModel(modelolista);
        this.listaServicios.setModel(modelolista);
        
        //llenamos la lista prestador
        this.listaPrestador.setListData(this.c.listarPrestadores().toArray());
        //desseleccionamos la lista prestador
        this.listaPrestador.clearSelection();
        
        //llenamos la lista productor
        this.listaProductor.setListData(this.c.listarProductores().toArray());
        //desseleccionamos la lista productor
        this.listaProductor.clearSelection();
        
        //llenamos la lista Servicios
        this.listaServicios.setListData(this.c.listarTiposServicios().toArray());
        //desseleccionamos la lista prestador
        this.listaPrestador.clearSelection();
        
    }
     
     
    private void listaPrestadorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPrestadorValueChanged
        //si la lista prestador esta seleccionada listamos los servicios de ese prestador
        if(!this.listaPrestador.isSelectionEmpty()){
            Prestador p = (Prestador) this.listaPrestador.getSelectedValue();
            this.listaServiciosPrestador.setListData(p.getServiciosPrestador().toArray());   
        }
    }//GEN-LAST:event_listaPrestadorValueChanged

    private void listaServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaServiciosValueChanged
        if(!this.listaServicios.isSelectionEmpty()){
            TipoServicio s = (TipoServicio) this.listaServicios.getSelectedValue();
            ArrayList<Prestador> pres = new ArrayList<Prestador>();
            for (int i = 0; i < s.getServiciosPrestador().size(); i++) {
                pres.add(s.getServiciosPrestador().get(i).getPrestador());
            }
            this.listaPrestadoresServicios.setListData(pres.toArray());
        }
    }//GEN-LAST:event_listaServiciosValueChanged

    private void listaProductorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaProductorValueChanged
    //si la lista productor esta seleccionada listamos los puntajes de ese productor
        if(!this.listaProductor.isSelectionEmpty()){
            Productor p = (Productor) this.listaProductor.getSelectedValue();
            this.listaHistorialPuntajes.setListData(this.c.listarHistorialPuntajes(p).toArray());
            
        }
    }//GEN-LAST:event_listaProductorValueChanged

    private void listaHistorialPuntajesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaHistorialPuntajesValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaHistorialPuntajesValueChanged

    private void listaServiciosPrestadorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaServiciosPrestadorValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaServiciosPrestadorValueChanged

    private void listaPrestadoresServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPrestadoresServiciosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaPrestadoresServiciosValueChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Label label6;
    private javax.swing.JList listaHistorialPuntajes;
    private javax.swing.JList listaPrestador;
    private javax.swing.JList listaPrestadoresServicios;
    private javax.swing.JList listaProductor;
    private javax.swing.JList listaServicios;
    private javax.swing.JList listaServiciosPrestador;
    // End of variables declaration//GEN-END:variables
}
